### ISSUE TITLE
Erros when running finetune

### ISSUE THREAD

**Issue by yenchenlin** [cvondrick/soundnet#2]
Hello @cvondrick ,

It seems that `audio_simple`, the `dataset` variable defined in `main_finetune.lua`, is not valid for `data.lua` to load the input audios. It shows following error:

```
/home/yclin/distro/install/bin/luajit: /home/yclin/Workspace/soundnet/data/data.lua:24: Unknown dataset: audio_simple
```

I also tried to replace `audio_simple` with `donkey_audio` and `donkey_audio_labeled`, but none of them work.

Would you please have a look in the finetune section of README?

**Comment by cvondrick** [comment]
Sorry for the typo. The correct name of the data loader is 'audio_labeled'
