### ISSUE TITLE
Tips on crawling images from video

### ISSUE THREAD

**Issue by keunwoochoi** [cvondrick/soundnet#7]
Hi, I'd like to ask some tips that would be generally applicable in video/image stuff deep learning, I've been only working on music-related works. Some (if not all) might seem dumb ;) 

* What would be good image format of extracted frames of video? jpeg or png?
* What was image *sampling* rate in the work? -- how many images per second did you sample?
* Any other tip/hack would be appreciated. 

Thanks!

**Comment by cvondrick** [comment]
1. I would recommend JPEG.
2. We extracted 1 frame per second.
3. Video is huge, so I recommend designing efficient ways of storing them!
