### ISSUE TITLE
where can I find soundnet8_final.lua

### ISSUE THREAD

**Issue by smallsheep666** [cvondrick/soundnet#8]
I just simply run demo.lua and it end up with:
lua: cannot open <models/soundnet8_final.lua> in mode r  at /home/yangshuo/torch/pkg/torch/lib/TH/THDiskFile.c:670
I searched https://projects.csail.mit.edu/soundnet/ and git,but I still not find  soundnet8_final.lua.
where can i find it

**Comment by ardasnck** [comment]
You can find it under the Section "Code&Trained Models" of project page. Just download the Pretrained Models(101 MB zip file).
