### ISSUE TITLE
Are the class probabilities for the MP3s released?

### ISSUE THREAD

**Issue by thisisjl** [cvondrick/soundnet#9]
Hi, in the [Soundnet website](https://projects.csail.mit.edu/soundnet/) I can see the MP3s are available to download, but I do not see their corresponding class probabilities.
Are they not available yet? Otherwise could you point me where I can find them?
Thanks

**Comment by MaigoAkisame** [comment]
They are in the "Image Features" archive.

**Comment by cvondrick** [comment]
Yes, they are the image features.
